#include "i2s.h"

void I2S_Init(void) {
  RCC->APB1ENR |= RCC_APB1ENR_SPI2EN;
  RCC->APB2ENR |= RCC_APB2ENR_IOPBEN;

  // PB13 - I2S_CK, AF push-pull, 2MHz
  GPIOB->CRH &= ~(GPIO_CRH_CNF13 | GPIO_CRH_MODE13);
  GPIOB->CRH |= GPIO_CRH_MODE13_1 | GPIO_CRH_CNF13_1;
  // PB12 - I2S_WS, AF push-pull, 2MHz
  GPIOB->CRH &= ~(GPIO_CRH_CNF12 | GPIO_CRH_MODE12);
  GPIOB->CRH |= GPIO_CRH_MODE12_1 | GPIO_CRH_CNF12_1;
  // PB15 - I2S_SD(transmitter), AF push-pull, 2MHz
  GPIOB->CRH &= ~(GPIO_CRH_CNF15 | GPIO_CRH_MODE15);
  GPIOB->CRH |= GPIO_CRH_MODE15_1 | GPIO_CRH_CNF15_1;

  SPI2->I2SCFGR = 0;
  SPI2->I2SCFGR |= SPI_I2SCFGR_I2SMOD | SPI_I2SCFGR_I2SCFG_1;

  SPI2->I2SPR = 0;
  SPI2->I2SPR |= SPI_I2SPR_ODD;
  SPI2->I2SPR |= (12 << SPI_I2SPR_I2SDIV_Pos);

  SPI2->I2SCFGR |= SPI_I2SCFGR_I2SE;
}